# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/yy/Desktop/to_be_sped_up/v2/vivado-library-master/if/pmod_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/vivado-library-master/ip/Pmods/PmodWIFI_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/img_proc_full
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/vivado-library-master/if/pmod_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/vivado-library-master/ip/Pmods/PmodWIFI_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/vivado-library-master/ip/Pmods/Pmod_Bridge_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/Downloads/vivado-library-master/if/pmod_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/Downloads/vivado-library-master/ip/Pmods/Pmod_Bridge_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/Downloads/vivado-library-master/ip/Pmods/PmodWIFI_v1_0
  c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/PWM
} [current_project]
set_property ip_cache_permissions disable [current_project]
add_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/edge_ram_init.coe
add_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/img_proc_full/jpeg.srcs/sources_1/coe_files/640x480.coe
add_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/coe_files/640x480.coe
add_files -quiet c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0.dcp
set_property used_in_implementation false [get_files c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0.dcp]
add_files -quiet c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
add_files -quiet c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp
set_property used_in_implementation false [get_files c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp]
add_files -quiet c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.dcp
set_property used_in_implementation false [get_files c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.dcp]
add_files -quiet c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.dcp
set_property used_in_implementation false [get_files c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.dcp]
add_files -quiet c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/img_proc_full/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.dcp
set_property used_in_implementation false [get_files c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/img_proc_full/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.dcp]
read_mem C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/ht_nr_of_symbols/jpeg_ht_nr_of_symbols.mif
read_verilog -library xil_defaultlib C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_vhdl -library xil_defaultlib {
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/upsampling_buffer/jpeg_upsampling_buffer.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/qt_table/jpeg_qt_sr.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/idct/jpeg_idct_core_12.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/huffman_input_sr/jpeg_huffman_input_sr.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/ht_tables/jpeg_ht_tables.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/ht_nr_of_symbols/jpeg_ht_nr_of_symbols.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/dequantize_multiplier/jpeg_dequant_multiplier.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_YCbCr2RGB.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_upsampling.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/input_fifo/jpeg_input_fifo.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_idct.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_huffman.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_header.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_dezigzag.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_dequantize.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_check_FF.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/check_FF_fifo/jpeg_checkff_fifo.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_input_fifo.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_checkff_fifo.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/vhdl/jpeg_qt_tables.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/idct/jpeg_idct_core_6.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/vhdl/fifo_sim32.vhd
  C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/vga_memory/vga_memory.vhd
}
add_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_81M_0/design_1_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_81M_0/design_1_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_81M_0/design_1_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/design_1_PmodWIFI_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/design_1_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_axi_intc_0/design_1_microblaze_1_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_axi_intc_0/design_1_microblaze_1_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_axi_intc_0/design_1_microblaze_1_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_MB1_GPIO_0/design_1_MB1_GPIO_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_MB1_GPIO_0/design_1_MB1_GPIO_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_MB1_GPIO_0/design_1_MB1_GPIO_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0_1/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0_1/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_0_1/design_1_auto_rs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_0_1/design_1_auto_rs_w_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1_1/design_1_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_1_1/design_1_auto_rs_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_1_1/design_1_auto_rs_w_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2_1/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2_1/design_1_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_2_1/design_1_auto_rs_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_2_1/design_1_auto_rs_w_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3_1/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3_1/design_1_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_3_1/design_1_auto_rs_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_3_1/design_1_auto_rs_w_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4_1/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4_1/design_1_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_4_1/design_1_auto_rs_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_4_1/design_1_auto_rs_w_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_5_1/design_1_auto_rs_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5_1/design_1_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5_1/design_1_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_6_1/design_1_auto_rs_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_5_1/design_1_auto_rs_w_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_7_1/design_1_auto_rs_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_6_1/design_1_auto_rs_w_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2_1/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2_1/design_1_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_8_1/design_1_auto_rs_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_7_1/design_1_auto_rs_w_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_6_1/design_1_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_6_1/design_1_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_9_1/design_1_auto_rs_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_8_1/design_1_auto_rs_w_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_7_1/design_1_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_7_1/design_1_auto_ds_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_10_1/design_1_auto_rs_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_8_1/design_1_auto_ds_8_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_8_1/design_1_auto_ds_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2_1/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_11_1/design_1_auto_rs_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_9_1/design_1_auto_rs_w_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_9_1/design_1_auto_ds_9_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_9_1/design_1_auto_ds_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3_1/design_1_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_10_1/design_1_auto_ds_10_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_10_1/design_1_auto_ds_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4_1/design_1_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_11_1/design_1_auto_ds_11_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_11_1/design_1_auto_ds_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_5_1/design_1_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_6_1/design_1_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3_1/design_1_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3_1/design_1_auto_us_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_12_1/design_1_auto_rs_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_10_1/design_1_auto_rs_w_10_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd]

read_ip -quiet C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xci]

read_ip -quiet C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xci]

read_ip -quiet C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xci]

read_ip -quiet C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xci]

read_ip -quiet C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/check_FF_fifo/jpeg_checkff_fifo_fifo_generator_v2_3_xst_1.ngc
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/check_FF_fifo/jpeg_checkff_fifo_fifo_generator_v2_3_xst_1_blkmemdp_v6_2_xst.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/upsampling_buffer/jpeg_upsampling_buffer.ngc
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/qt_table/jpeg_qt_sr.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/idct/jpeg_idct_core_12.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/huffman_input_sr/jpeg_huffman_input_sr.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/ht_tables/jpeg_ht_tables.ngc
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/ht_nr_of_symbols/jpeg_ht_nr_of_symbols.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/dequantize_multiplier/jpeg_dequant_multiplier.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/input_fifo/jpeg_input_fifo.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/src/jpeg_checkff_fifo.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/qt_table/jpeg_qt_sr_c_shift_ram_v8_0_xst_1.ngc
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/input_fifo/jpeg_input_fifo_fifo_generator_v2_3_xst_1_blkmemdp_v6_2_xst.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/input_fifo/jpeg_input_fifo_fifo_generator_v2_3_xst_1.ngc
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/idct/jpeg_idct_core_6.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/dequantize_multiplier/jpeg_dequant_multiplier_mult_gen_v8_0_xst_1.ngc
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/check_FF_fifo/jpeg_checkff_fifo.edn
read_edif C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/imports/coregen/vga_memory/vga_memory.ngc
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/constrs_1/imports/const.xdc
set_property used_in_implementation false [get_files C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/constrs_1/imports/const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a100tcsg324-1 -fanout_limit 400 -retiming -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
