# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/const.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0}]

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0}]

# IP: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0}]

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0}]

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_0/design_1_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_0}]

# IP: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0}]

# IP: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0}]

# IP: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0}]

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_81M_0/design_1_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==design_1_rst_mig_7series_0_81M_0}]

# IP: bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0 || ORIG_REF_NAME==design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0}]

# IP: bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_1 || ORIG_REF_NAME==design_1_lmb_bram_1}]

# IP: bd/design_1/ip/design_1_PmodWIFI_0_0/design_1_PmodWIFI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PmodWIFI_0_0 || ORIG_REF_NAME==design_1_PmodWIFI_0_0}]

# IP: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_pmod_bridge_0_0 || ORIG_REF_NAME==PmodWIFI_pmod_bridge_0_0}]

# IP: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}]

# IP: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}]

# IP: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}]

# IP: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}]

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}]

# IP: bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_0 || ORIG_REF_NAME==design_1_microblaze_1_0}]

# IP: bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_1 || ORIG_REF_NAME==design_1_dlmb_v10_1}]

# IP: bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_1 || ORIG_REF_NAME==design_1_ilmb_v10_1}]

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/design_1_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_1}]

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_1}]

# IP: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0}]

# IP: bd/design_1/ip/design_1_microblaze_1_axi_periph_0/design_1_microblaze_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_1_axi_periph_0}]

# IP: bd/design_1/ip/design_1_microblaze_1_axi_intc_0/design_1_microblaze_1_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_1_axi_intc_0}]

# IP: bd/design_1/ip/design_1_microblaze_1_xlconcat_0/design_1_microblaze_1_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_1_xlconcat_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_1/design_1_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_1}]

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0}]

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0}]

# IP: bd/design_1/ip/design_1_MB1_GPIO_0/design_1_MB1_GPIO_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MB1_GPIO_0 || ORIG_REF_NAME==design_1_MB1_GPIO_0}]

# IP: bd/design_1/ip/design_1_switch_led_out_0_0/design_1_switch_led_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_switch_led_out_0_0 || ORIG_REF_NAME==design_1_switch_led_out_0_0}]

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1}]

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2}]

# IP: bd/design_1/ip/design_1_auto_ds_0_1/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0}]

# IP: bd/design_1/ip/design_1_auto_rs_0_1/design_1_auto_rs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_0 || ORIG_REF_NAME==design_1_auto_rs_0}]

# IP: bd/design_1/ip/design_1_auto_rs_w_0_1/design_1_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_0 || ORIG_REF_NAME==design_1_auto_rs_w_0}]

# IP: bd/design_1/ip/design_1_auto_ds_1_1/design_1_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1}]

# IP: bd/design_1/ip/design_1_auto_rs_1_1/design_1_auto_rs_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_1 || ORIG_REF_NAME==design_1_auto_rs_1}]

# IP: bd/design_1/ip/design_1_auto_rs_w_1_1/design_1_auto_rs_w_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_1 || ORIG_REF_NAME==design_1_auto_rs_w_1}]

# IP: bd/design_1/ip/design_1_auto_ds_2_1/design_1_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_2 || ORIG_REF_NAME==design_1_auto_ds_2}]

# IP: bd/design_1/ip/design_1_auto_rs_2_1/design_1_auto_rs_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_2 || ORIG_REF_NAME==design_1_auto_rs_2}]

# IP: bd/design_1/ip/design_1_auto_rs_w_2_1/design_1_auto_rs_w_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_2 || ORIG_REF_NAME==design_1_auto_rs_w_2}]

# IP: bd/design_1/ip/design_1_auto_ds_3_1/design_1_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_3 || ORIG_REF_NAME==design_1_auto_ds_3}]

# IP: bd/design_1/ip/design_1_auto_rs_3_1/design_1_auto_rs_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_3 || ORIG_REF_NAME==design_1_auto_rs_3}]

# IP: bd/design_1/ip/design_1_auto_rs_w_3_1/design_1_auto_rs_w_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_3 || ORIG_REF_NAME==design_1_auto_rs_w_3}]

# IP: bd/design_1/ip/design_1_auto_ds_4_1/design_1_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_4 || ORIG_REF_NAME==design_1_auto_ds_4}]

# IP: bd/design_1/ip/design_1_auto_rs_4_1/design_1_auto_rs_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_4 || ORIG_REF_NAME==design_1_auto_rs_4}]

# IP: bd/design_1/ip/design_1_auto_rs_w_4_1/design_1_auto_rs_w_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_4 || ORIG_REF_NAME==design_1_auto_rs_w_4}]

# IP: bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# IP: bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0}]

# IP: bd/design_1/ip/design_1_auto_rs_5_1/design_1_auto_rs_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_5 || ORIG_REF_NAME==design_1_auto_rs_5}]

# IP: bd/design_1/ip/design_1_auto_ds_5_1/design_1_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_5 || ORIG_REF_NAME==design_1_auto_ds_5}]

# IP: bd/design_1/ip/design_1_auto_rs_6_1/design_1_auto_rs_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_6 || ORIG_REF_NAME==design_1_auto_rs_6}]

# IP: bd/design_1/ip/design_1_auto_rs_w_5_1/design_1_auto_rs_w_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_5 || ORIG_REF_NAME==design_1_auto_rs_w_5}]

# IP: bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1}]

# IP: bd/design_1/ip/design_1_auto_rs_7_1/design_1_auto_rs_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_7 || ORIG_REF_NAME==design_1_auto_rs_7}]

# IP: bd/design_1/ip/design_1_auto_rs_w_6_1/design_1_auto_rs_w_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_6 || ORIG_REF_NAME==design_1_auto_rs_w_6}]

# IP: bd/design_1/ip/design_1_auto_us_2_1/design_1_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2}]

# IP: bd/design_1/ip/design_1_auto_rs_8_1/design_1_auto_rs_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_8 || ORIG_REF_NAME==design_1_auto_rs_8}]

# IP: bd/design_1/ip/design_1_auto_rs_w_7_1/design_1_auto_rs_w_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_7 || ORIG_REF_NAME==design_1_auto_rs_w_7}]

# IP: bd/design_1/ip/design_1_auto_ds_6_1/design_1_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_6 || ORIG_REF_NAME==design_1_auto_ds_6}]

# IP: bd/design_1/ip/design_1_auto_pc_1_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1}]

# IP: bd/design_1/ip/design_1_auto_rs_9_1/design_1_auto_rs_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_9 || ORIG_REF_NAME==design_1_auto_rs_9}]

# IP: bd/design_1/ip/design_1_auto_rs_w_8_1/design_1_auto_rs_w_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_8 || ORIG_REF_NAME==design_1_auto_rs_w_8}]

# IP: bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}]

# IP: bd/design_1/ip/design_1_auto_ds_7_1/design_1_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_7 || ORIG_REF_NAME==design_1_auto_ds_7}]

# IP: bd/design_1/ip/design_1_auto_rs_10_1/design_1_auto_rs_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_10 || ORIG_REF_NAME==design_1_auto_rs_10}]

# IP: bd/design_1/ip/design_1_auto_ds_8_1/design_1_auto_ds_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_8 || ORIG_REF_NAME==design_1_auto_ds_8}]

# IP: bd/design_1/ip/design_1_auto_pc_2_1/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2}]

# IP: bd/design_1/ip/design_1_auto_rs_11_1/design_1_auto_rs_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_11 || ORIG_REF_NAME==design_1_auto_rs_11}]

# IP: bd/design_1/ip/design_1_auto_rs_w_9_1/design_1_auto_rs_w_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_9 || ORIG_REF_NAME==design_1_auto_rs_w_9}]

# IP: bd/design_1/ip/design_1_auto_ds_9_1/design_1_auto_ds_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_9 || ORIG_REF_NAME==design_1_auto_ds_9}]

# IP: bd/design_1/ip/design_1_auto_pc_3_1/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3}]

# IP: bd/design_1/ip/design_1_auto_ds_10_1/design_1_auto_ds_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_10 || ORIG_REF_NAME==design_1_auto_ds_10}]

# IP: bd/design_1/ip/design_1_auto_pc_4_1/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4}]

# IP: bd/design_1/ip/design_1_auto_ds_11_1/design_1_auto_ds_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_11 || ORIG_REF_NAME==design_1_auto_ds_11}]

# IP: bd/design_1/ip/design_1_auto_pc_5_1/design_1_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5}]

# IP: bd/design_1/ip/design_1_auto_pc_6_1/design_1_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_6 || ORIG_REF_NAME==design_1_auto_pc_6}]

# IP: bd/design_1/ip/design_1_auto_us_3_1/design_1_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3}]

# IP: bd/design_1/ip/design_1_auto_rs_12_1/design_1_auto_rs_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_12 || ORIG_REF_NAME==design_1_auto_rs_12}]

# IP: bd/design_1/ip/design_1_auto_rs_w_10_1/design_1_auto_rs_w_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_10 || ORIG_REF_NAME==design_1_auto_rs_w_10}]

# IP: ip/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}]

# IP: ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}]

# IP: ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}]

# IP: ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}]

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1}]

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc

# XDC: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0}]

# XDC: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_rst_mig_7series_0_81M_0/design_1_rst_mig_7series_0_81M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==design_1_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_rst_mig_7series_0_81M_0/design_1_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==design_1_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_rst_mig_7series_0_81M_0/design_1_rst_mig_7series_0_81M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0 || ORIG_REF_NAME==design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/design_1_PmodWIFI_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_PmodWIFI_0_0 || ORIG_REF_NAME==design_1_PmodWIFI_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_pmod_bridge_0_0 || ORIG_REF_NAME==PmodWIFI_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_PmodWIFI_0_0/src/PmodWIFI_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_0 || ORIG_REF_NAME==design_1_microblaze_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0_ooc_debug.xdc

# XDC: bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_1 || ORIG_REF_NAME==design_1_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_1 || ORIG_REF_NAME==design_1_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/design_1_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_microblaze_1_axi_intc_0/design_1_microblaze_1_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_1_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_1_axi_intc_0/design_1_microblaze_1_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_1_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_1_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_1_axi_intc_0/design_1_microblaze_1_axi_intc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_MB1_GPIO_0/design_1_MB1_GPIO_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_MB1_GPIO_0 || ORIG_REF_NAME==design_1_MB1_GPIO_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_MB1_GPIO_0/design_1_MB1_GPIO_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_MB1_GPIO_0/design_1_MB1_GPIO_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_MB1_GPIO_0 || ORIG_REF_NAME==design_1_MB1_GPIO_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_0_1/design_1_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_0_1/design_1_auto_ds_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_0_1/design_1_auto_rs_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_0_1/design_1_auto_rs_w_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_1_1/design_1_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_1_1/design_1_auto_ds_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_1_1/design_1_auto_rs_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_1_1/design_1_auto_rs_w_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_2_1/design_1_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_2 || ORIG_REF_NAME==design_1_auto_ds_2}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_2_1/design_1_auto_ds_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_2_1/design_1_auto_rs_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_2_1/design_1_auto_rs_w_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_3_1/design_1_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_3 || ORIG_REF_NAME==design_1_auto_ds_3}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_3_1/design_1_auto_ds_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_3_1/design_1_auto_rs_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_3_1/design_1_auto_rs_w_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_4_1/design_1_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_4 || ORIG_REF_NAME==design_1_auto_ds_4}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_4_1/design_1_auto_ds_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_4_1/design_1_auto_rs_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_4_1/design_1_auto_rs_w_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_5_1/design_1_auto_rs_5_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_5_1/design_1_auto_ds_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_5 || ORIG_REF_NAME==design_1_auto_ds_5}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_5_1/design_1_auto_ds_5_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_6_1/design_1_auto_rs_6_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_5_1/design_1_auto_rs_w_5_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_7_1/design_1_auto_rs_7_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_6_1/design_1_auto_rs_w_6_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_2_1/design_1_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_2_1/design_1_auto_us_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_8_1/design_1_auto_rs_8_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_7_1/design_1_auto_rs_w_7_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_6_1/design_1_auto_ds_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_6 || ORIG_REF_NAME==design_1_auto_ds_6}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_6_1/design_1_auto_ds_6_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_1_1/design_1_auto_pc_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_9_1/design_1_auto_rs_9_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_8_1/design_1_auto_rs_w_8_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_7_1/design_1_auto_ds_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_7 || ORIG_REF_NAME==design_1_auto_ds_7}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_7_1/design_1_auto_ds_7_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_10_1/design_1_auto_rs_10_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_8_1/design_1_auto_ds_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_8 || ORIG_REF_NAME==design_1_auto_ds_8}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_8_1/design_1_auto_ds_8_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_2_1/design_1_auto_pc_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_11_1/design_1_auto_rs_11_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_9_1/design_1_auto_rs_w_9_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_9_1/design_1_auto_ds_9_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_9 || ORIG_REF_NAME==design_1_auto_ds_9}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_9_1/design_1_auto_ds_9_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_3_1/design_1_auto_pc_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_10_1/design_1_auto_ds_10_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_10 || ORIG_REF_NAME==design_1_auto_ds_10}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_10_1/design_1_auto_ds_10_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_4_1/design_1_auto_pc_4_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_11_1/design_1_auto_ds_11_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_11 || ORIG_REF_NAME==design_1_auto_ds_11}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_ds_11_1/design_1_auto_ds_11_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_5_1/design_1_auto_pc_5_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_6_1/design_1_auto_pc_6_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_us_3_1/design_1_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_us_3_1/design_1_auto_us_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_12_1/design_1_auto_rs_12_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_rs_w_10_1/design_1_auto_rs_w_10_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc

# XDC: ip/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: ip/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc

# XDC: ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc

# XDC: ip/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc

# XDC: ip/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc

# XDC: ip/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
