# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/IBM_ADMIN/Desktop/yy/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0.xci
# IP: The module: 'PmodWIFI_pmod_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IBM_ADMIN/Desktop/yy/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodWIFI_pmod_bridge_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/IBM_ADMIN/Desktop/yy/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodWIFI_pmod_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/IBM_ADMIN/Desktop/yy/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0.xci
# IP: The module: 'PmodWIFI_pmod_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IBM_ADMIN/Desktop/yy/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodWIFI_pmod_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/IBM_ADMIN/Desktop/yy/project_1/project_1.srcs/sources_1/ip/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodWIFI_pmod_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
