# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.cache/wt [current_project]
set_property parent.project_path C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_mem {
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/ht_nr_of_symbols/jpeg_ht_nr_of_symbols.mif
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/img.mif
}
read_verilog -library xil_defaultlib {
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/edge_detector.v
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/image_processor.v
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/vga_controller.v
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/stream_jpg_yy_nv_mn_v1_0.v
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/stream_jpg_yy_nv_mn_v1_0_S00_AXIS.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_upsampling_buffer.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_qt_sr.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_idct_core_12.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_huffman_input_sr.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_ht_tables.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_ht_nr_of_symbols.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_dequant_multiplier.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/upsampling_buffer/jpeg_upsampling_buffer.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/qt_table/jpeg_qt_sr.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/idct/jpeg_idct_core_12.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/huffman_input_sr/jpeg_huffman_input_sr.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/ht_tables/jpeg_ht_tables.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/ht_nr_of_symbols/jpeg_ht_nr_of_symbols.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/dequantize_multiplier/jpeg_dequant_multiplier.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_YCbCr2RGB.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_upsampling.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_input_fifo.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_idct.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_huffman.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_header.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_dezigzag.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_dequantize.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_check_FF.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_checkff_fifo.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/input_fifo/jpeg_input_fifo.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/check_FF_fifo/jpeg_checkff_fifo.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/jpeg_qt_tables.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/idct/jpeg_idct_core_6.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/pcores/myipif/hdl/vhdl/fifo_sim32.vhd
  C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/vga_driver.vhd
}
read_ip -quiet C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

read_ip -quiet C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci]

read_ip -quiet C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci]

read_ip -quiet C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

read_ip -quiet C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_ip -quiet C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all c:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]
set_property is_locked true [get_files C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci]

read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/check_FF_fifo/jpeg_checkff_fifo_fifo_generator_v2_3_xst_1.ngc
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/check_FF_fifo/jpeg_checkff_fifo_fifo_generator_v2_3_xst_1_blkmemdp_v6_2_xst.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/upsampling_buffer/jpeg_upsampling_buffer.ngc
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/qt_table/jpeg_qt_sr.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/idct/jpeg_idct_core_12.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/huffman_input_sr/jpeg_huffman_input_sr.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/ht_tables/jpeg_ht_tables.ngc
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/ht_nr_of_symbols/jpeg_ht_nr_of_symbols.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/dequantize_multiplier/jpeg_dequant_multiplier.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/input_fifo/jpeg_input_fifo.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/check_FF_fifo/jpeg_checkff_fifo.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/qt_table/jpeg_qt_sr_c_shift_ram_v8_0_xst_1.ngc
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/input_fifo/jpeg_input_fifo_fifo_generator_v2_3_xst_1_blkmemdp_v6_2_xst.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/input_fifo/jpeg_input_fifo_fifo_generator_v2_3_xst_1.ngc
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/idct/jpeg_idct_core_6.edn
read_edif C:/Users/yy/Desktop/ece532_debug/img_proc_full/jpeg.srcs/sources_1/imports/mjpeg/coregen/dequantize_multiplier/jpeg_dequant_multiplier_mult_gen_v8_0_xst_1.ngc
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top stream_jpg_yy_nv_mn_v1_0 -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef stream_jpg_yy_nv_mn_v1_0.dcp

catch { report_utilization -file stream_jpg_yy_nv_mn_v1_0_utilization_synth.rpt -pb stream_jpg_yy_nv_mn_v1_0_utilization_synth.pb }
