set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/ece532_debug/tr3/yy/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc rfile:../project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/microblaze_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/ece532_debug/tr3/yy/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc rfile:../project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc id:2 order:EARLY scoped_inst:design_1_i/mdm_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/ece532_debug/tr3/yy/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc rfile:../project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc id:3 order:EARLY scoped_inst:design_1_i/clk_wiz_1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/ece532_debug/tr3/yy/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc rfile:../project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc id:4 order:EARLY scoped_inst:design_1_i/mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/yy/Desktop/ece532_debug/tr3/yy/project_1/project_1.srcs/constrs_1/imports/const.xdc rfile:../project_1.srcs/constrs_1/imports/const.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/yy/Desktop/ece532_debug/tr3/yy/project_1/project_1.srcs/constrs_1/imports/img_proc_full.xdc rfile:../project_1.srcs/constrs_1/imports/img_proc_full.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/ece532_debug/tr3/yy/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc rfile:../project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc id:7 order:LATE scoped_inst:design_1_i/microblaze_0_axi_periph/m06_couplers/auto_cc/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { DPOP-3 PDCN-1569 CDC-1 CDC-4 CDC-7 TIMING-9 TIMING-10 }
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { CDC-1 CDCM-1 REQP-1851 TIMING-2 TIMING-4 TIMING-9 TIMING-10 TIMING-14 }
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:SCOPED_XDC file:4 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:4 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:4 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:4 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:4 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:4 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:4 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:4 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:4 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:4 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:4 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr2_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:XDC file:5 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst_n_123]]
set_property src_info {type:XDC file:5 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/ready]]
set_property src_info {type:XDC file:5 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/s00_axis_tready]]
set_property src_info {type:XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst/s00_axis_aresetn]]
set_property src_info {type:XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst/jpeg_dezigzag_p/ready_o]]
set_property src_info {type:XDC file:5 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst/jpeg_huffman_p/ready_o]]
set_property src_info {type:XDC file:6 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/yy_ready_o]]
set_property src_info {type:XDC file:6 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:6 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:6 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:6 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_1/inst/clk_out1]]
set_property src_info {type:XDC file:6 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:6 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:6 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[1]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[2]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[3]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[4]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[5]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[6]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[7]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[8]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[9]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[10]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[11]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[12]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[13]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[14]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[15]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[16]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[17]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[18]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[19]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[20]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[21]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[22]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[23]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[24]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[25]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[26]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[27]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[28]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[29]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[30]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[31]}]]
set_property src_info {type:XDC file:6 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:6 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:6 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[1]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[2]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[3]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[4]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[5]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[6]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[7]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[8]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[9]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[10]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[11]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[12]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[13]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[14]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[15]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[16]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[17]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[18]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[19]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[20]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[21]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[22]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[23]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[24]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[25]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[26]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[27]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[28]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[29]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[30]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[31]}]]
set_property src_info {type:XDC file:6 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:6 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:6 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/next_state[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/next_state[1]}]]
set_property src_info {type:XDC file:6 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:6 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:6 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/state[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/state[1]}]]
set_property src_info {type:XDC file:6 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:6 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:6 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/microblaze_0_M0_AXIS_TDATA[0]} {design_1_i/microblaze_0_M0_AXIS_TDATA[1]} {design_1_i/microblaze_0_M0_AXIS_TDATA[2]} {design_1_i/microblaze_0_M0_AXIS_TDATA[3]} {design_1_i/microblaze_0_M0_AXIS_TDATA[4]} {design_1_i/microblaze_0_M0_AXIS_TDATA[5]} {design_1_i/microblaze_0_M0_AXIS_TDATA[6]} {design_1_i/microblaze_0_M0_AXIS_TDATA[7]} {design_1_i/microblaze_0_M0_AXIS_TDATA[8]} {design_1_i/microblaze_0_M0_AXIS_TDATA[9]} {design_1_i/microblaze_0_M0_AXIS_TDATA[10]} {design_1_i/microblaze_0_M0_AXIS_TDATA[11]} {design_1_i/microblaze_0_M0_AXIS_TDATA[12]} {design_1_i/microblaze_0_M0_AXIS_TDATA[13]} {design_1_i/microblaze_0_M0_AXIS_TDATA[14]} {design_1_i/microblaze_0_M0_AXIS_TDATA[15]} {design_1_i/microblaze_0_M0_AXIS_TDATA[16]} {design_1_i/microblaze_0_M0_AXIS_TDATA[17]} {design_1_i/microblaze_0_M0_AXIS_TDATA[18]} {design_1_i/microblaze_0_M0_AXIS_TDATA[19]} {design_1_i/microblaze_0_M0_AXIS_TDATA[20]} {design_1_i/microblaze_0_M0_AXIS_TDATA[21]} {design_1_i/microblaze_0_M0_AXIS_TDATA[22]} {design_1_i/microblaze_0_M0_AXIS_TDATA[23]} {design_1_i/microblaze_0_M0_AXIS_TDATA[24]} {design_1_i/microblaze_0_M0_AXIS_TDATA[25]} {design_1_i/microblaze_0_M0_AXIS_TDATA[26]} {design_1_i/microblaze_0_M0_AXIS_TDATA[27]} {design_1_i/microblaze_0_M0_AXIS_TDATA[28]} {design_1_i/microblaze_0_M0_AXIS_TDATA[29]} {design_1_i/microblaze_0_M0_AXIS_TDATA[30]} {design_1_i/microblaze_0_M0_AXIS_TDATA[31]}]]
set_property src_info {type:XDC file:6 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:6 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:6 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/almost_full]]
set_property src_info {type:XDC file:6 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:6 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:6 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/datavalid_i]]
set_property src_info {type:XDC file:6 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:6 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:6 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/empty]]
set_property src_info {type:XDC file:6 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:6 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:6 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/full]]
set_property src_info {type:XDC file:6 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:6 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:6 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/microblaze_0_M0_AXIS_TREADY]]
set_property src_info {type:XDC file:6 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:6 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:6 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/microblaze_0_M0_AXIS_TVALID]]
set_property src_info {type:XDC file:6 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:6 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:6 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/rd_en]]
set_property src_info {type:XDC file:6 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:6 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:6 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/ready]]
set_property src_info {type:XDC file:6 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:6 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:6 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/rst_clk_wiz_1_100M_peripheral_aresetn]]
set_property src_info {type:XDC file:6 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:6 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:6 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tready]]
set_property src_info {type:XDC file:6 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:6 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:6 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:6 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tvalid]]
set_property src_info {type:XDC file:6 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:6 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:6 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:6 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
set_property src_info {type:SCOPED_XDC file:7 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports m_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/microblaze_0_axi_periph/m06_couplers/auto_cc/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports s_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/microblaze_0_axi_periph/m06_couplers/auto_cc/inst/m_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
