set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc rfile:../../../project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/microblaze_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc rfile:../../../project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc id:2 order:EARLY scoped_inst:design_1_i/mdm_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc rfile:../../../project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc id:3 order:EARLY scoped_inst:design_1_i/clk_wiz_1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc rfile:../../../project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc id:4 order:EARLY scoped_inst:design_1_i/mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc rfile:../../../project_1.srcs/sources_1/bd/design_1/ip/design_1_stream_jpg_yy_nv_mn_v1_0_wed2_0_0/jpeg.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc id:5 order:EARLY scoped_inst:design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.xdc rfile:../../../project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.xdc id:6 order:EARLY scoped_inst:design_1_i/microblaze_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.srcs/constrs_1/imports/const.xdc rfile:../../../project_1.srcs/constrs_1/imports/const.xdc id:7} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/yy/Desktop/to_be_sped_up/v2/temp532/project_1/project_1.runs/synth_1/dont_touch.xdc rfile:../dont_touch.xdc id:8} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { DPOP-3 PDCN-1569 CDC-1 CDC-4 CDC-7 TIMING-9 TIMING-10 REQP-1839 }
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { CDC-1 CDCM-1 REQP-1851 TIMING-2 TIMING-4 TIMING-9 TIMING-10 TIMING-14 }
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:SCOPED_XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {ddr2_dq[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {ddr2_dq[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {ddr2_dq[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {ddr2_dq[3]}]
set_property src_info {type:SCOPED_XDC file:4 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {ddr2_dq[4]}]
set_property src_info {type:SCOPED_XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {ddr2_dq[5]}]
set_property src_info {type:SCOPED_XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {ddr2_dq[6]}]
set_property src_info {type:SCOPED_XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {ddr2_dq[7]}]
set_property src_info {type:SCOPED_XDC file:4 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {ddr2_dq[8]}]
set_property src_info {type:SCOPED_XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {ddr2_dq[9]}]
set_property src_info {type:SCOPED_XDC file:4 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {ddr2_dq[10]}]
set_property src_info {type:SCOPED_XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {ddr2_dq[11]}]
set_property src_info {type:SCOPED_XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {ddr2_dq[12]}]
set_property src_info {type:SCOPED_XDC file:4 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddr2_dq[13]}]
set_property src_info {type:SCOPED_XDC file:4 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {ddr2_dq[14]}]
set_property src_info {type:SCOPED_XDC file:4 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddr2_dq[15]}]
set_property src_info {type:SCOPED_XDC file:4 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {ddr2_addr[12]}]
set_property src_info {type:SCOPED_XDC file:4 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr2_addr[11]}]
set_property src_info {type:SCOPED_XDC file:4 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddr2_addr[10]}]
set_property src_info {type:SCOPED_XDC file:4 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {ddr2_addr[9]}]
set_property src_info {type:SCOPED_XDC file:4 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ddr2_addr[8]}]
set_property src_info {type:SCOPED_XDC file:4 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {ddr2_addr[7]}]
set_property src_info {type:SCOPED_XDC file:4 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {ddr2_addr[6]}]
set_property src_info {type:SCOPED_XDC file:4 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {ddr2_addr[5]}]
set_property src_info {type:SCOPED_XDC file:4 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ddr2_addr[4]}]
set_property src_info {type:SCOPED_XDC file:4 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {ddr2_addr[3]}]
set_property src_info {type:SCOPED_XDC file:4 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {ddr2_addr[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ddr2_addr[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {ddr2_addr[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ddr2_ba[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {ddr2_ba[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {ddr2_ba[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports {ddr2_ras_n}]
set_property src_info {type:SCOPED_XDC file:4 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {ddr2_cas_n}]
set_property src_info {type:SCOPED_XDC file:4 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports {ddr2_we_n}]
set_property src_info {type:SCOPED_XDC file:4 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {ddr2_cke[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports {ddr2_odt[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {ddr2_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {ddr2_dm[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {ddr2_dm[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {ddr2_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddr2_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {ddr2_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports {ddr2_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:4 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:4 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:4 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:4 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:4 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:4 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:4 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:4 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:4 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:4 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr2_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:SCOPED_XDC file:5 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_ports rst] -to [get_pins -hierarchical -filter {NAME =~ *rstblk*/*PRE}]
set_property src_info {type:SCOPED_XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells -hierarchical -filter {NAME =~ *rstblk*/*rst_reg_reg[*]}]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { DPOP-3 PDCN-1569 CDC-1 CDC-4 CDC-7 TIMING-9 TIMING-10 REQP-1839 }
set_property src_info {type:XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports pmod_out_pin1_io]
set_property src_info {type:XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports pmod_out_pin2_io]
set_property src_info {type:XDC file:7 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports pmod_out_pin3_io]
set_property src_info {type:XDC file:7 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports pmod_out_pin4_io]
set_property src_info {type:XDC file:7 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports pmod_out_pin7_io]
set_property src_info {type:XDC file:7 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports pmod_out_pin8_io]
set_property src_info {type:XDC file:7 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports pmod_out_pin9_io]
set_property src_info {type:XDC file:7 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports pmod_out_pin10_io]
set_property src_info {type:XDC file:7 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports sys_clock]
set_property src_info {type:XDC file:7 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst_n_123]]
set_property src_info {type:XDC file:7 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/ready]]
set_property src_info {type:XDC file:7 line:25 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/s00_axis_tready]]
set_property src_info {type:XDC file:7 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst/s00_axis_aresetn]]
set_property src_info {type:XDC file:7 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst/jpeg_dezigzag_p/ready_o]]
set_property src_info {type:XDC file:7 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/im_proc/jpeg_inst/jpeg_huffman_p/ready_o]]
set_property src_info {type:XDC file:7 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {R[0]}]
set_property src_info {type:XDC file:7 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {R[1]}]
set_property src_info {type:XDC file:7 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C5 [get_ports {R[2]}]
set_property src_info {type:XDC file:7 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {R[3]}]
set_property src_info {type:XDC file:7 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C6 [get_ports {G[0]}]
set_property src_info {type:XDC file:7 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {G[1]}]
set_property src_info {type:XDC file:7 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports {G[2]}]
set_property src_info {type:XDC file:7 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A6 [get_ports {G[3]}]
set_property src_info {type:XDC file:7 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7 [get_ports {B[0]}]
set_property src_info {type:XDC file:7 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports {B[1]}]
set_property src_info {type:XDC file:7 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D7 [get_ports {B[2]}]
set_property src_info {type:XDC file:7 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports {B[3]}]
set_property src_info {type:XDC file:7 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports H]
set_property src_info {type:XDC file:7 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B12 [get_ports V]
set_property src_info {type:XDC file:7 line:71 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/yy_ready_o]]
set_property src_info {type:XDC file:7 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:7 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:7 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:7 line:83 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_1/inst/clk_out1]]
set_property src_info {type:XDC file:7 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:7 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:7 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[1]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[2]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[3]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[4]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[5]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[6]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[7]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[8]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[9]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[10]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[11]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[12]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[13]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[14]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[15]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[16]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[17]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[18]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[19]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[20]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[21]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[22]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[23]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[24]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[25]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[26]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[27]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[28]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[29]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[30]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/dout[31]}]]
set_property src_info {type:XDC file:7 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:7 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:7 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[1]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[2]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[3]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[4]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[5]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[6]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[7]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[8]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[9]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[10]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[11]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[12]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[13]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[14]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[15]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[16]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[17]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[18]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[19]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[20]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[21]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[22]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[23]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[24]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[25]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[26]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[27]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[28]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[29]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[30]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tdata[31]}]]
set_property src_info {type:XDC file:7 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:7 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:7 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/next_state[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/next_state[1]}]]
set_property src_info {type:XDC file:7 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:7 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:7 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/state[0]} {design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/state[1]}]]
set_property src_info {type:XDC file:7 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:7 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:7 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/microblaze_0_M0_AXIS_TDATA[0]} {design_1_i/microblaze_0_M0_AXIS_TDATA[1]} {design_1_i/microblaze_0_M0_AXIS_TDATA[2]} {design_1_i/microblaze_0_M0_AXIS_TDATA[3]} {design_1_i/microblaze_0_M0_AXIS_TDATA[4]} {design_1_i/microblaze_0_M0_AXIS_TDATA[5]} {design_1_i/microblaze_0_M0_AXIS_TDATA[6]} {design_1_i/microblaze_0_M0_AXIS_TDATA[7]} {design_1_i/microblaze_0_M0_AXIS_TDATA[8]} {design_1_i/microblaze_0_M0_AXIS_TDATA[9]} {design_1_i/microblaze_0_M0_AXIS_TDATA[10]} {design_1_i/microblaze_0_M0_AXIS_TDATA[11]} {design_1_i/microblaze_0_M0_AXIS_TDATA[12]} {design_1_i/microblaze_0_M0_AXIS_TDATA[13]} {design_1_i/microblaze_0_M0_AXIS_TDATA[14]} {design_1_i/microblaze_0_M0_AXIS_TDATA[15]} {design_1_i/microblaze_0_M0_AXIS_TDATA[16]} {design_1_i/microblaze_0_M0_AXIS_TDATA[17]} {design_1_i/microblaze_0_M0_AXIS_TDATA[18]} {design_1_i/microblaze_0_M0_AXIS_TDATA[19]} {design_1_i/microblaze_0_M0_AXIS_TDATA[20]} {design_1_i/microblaze_0_M0_AXIS_TDATA[21]} {design_1_i/microblaze_0_M0_AXIS_TDATA[22]} {design_1_i/microblaze_0_M0_AXIS_TDATA[23]} {design_1_i/microblaze_0_M0_AXIS_TDATA[24]} {design_1_i/microblaze_0_M0_AXIS_TDATA[25]} {design_1_i/microblaze_0_M0_AXIS_TDATA[26]} {design_1_i/microblaze_0_M0_AXIS_TDATA[27]} {design_1_i/microblaze_0_M0_AXIS_TDATA[28]} {design_1_i/microblaze_0_M0_AXIS_TDATA[29]} {design_1_i/microblaze_0_M0_AXIS_TDATA[30]} {design_1_i/microblaze_0_M0_AXIS_TDATA[31]}]]
set_property src_info {type:XDC file:7 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:7 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:7 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/almost_full]]
set_property src_info {type:XDC file:7 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:7 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:7 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/datavalid_i]]
set_property src_info {type:XDC file:7 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:7 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:7 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/empty]]
set_property src_info {type:XDC file:7 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:7 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:7 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/full]]
set_property src_info {type:XDC file:7 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:7 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:7 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/microblaze_0_M0_AXIS_TREADY]]
set_property src_info {type:XDC file:7 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:7 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:7 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/microblaze_0_M0_AXIS_TVALID]]
set_property src_info {type:XDC file:7 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:7 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:7 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/rd_en]]
set_property src_info {type:XDC file:7 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:7 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:7 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/ready]]
set_property src_info {type:XDC file:7 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:7 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:7 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/rst_clk_wiz_1_100M_peripheral_aresetn]]
set_property src_info {type:XDC file:7 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:7 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:7 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tready]]
set_property src_info {type:XDC file:7 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:7 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:7 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:7 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/stream_jpg_yy_nv_mn_v1_0_wed2_0/inst/s00_axis_tvalid]]
set_property src_info {type:XDC file:7 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:7 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:7 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:7 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
set_property src_info {type:XDC file:7 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports calibrate]
set_property src_info {type:XDC file:7 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports reset_target]
set_property src_info {type:XDC file:7 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports error_o]
set_property src_info {type:XDC file:7 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports reset_yy]
set_property src_info {type:XDC file:7 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports edge_2k]
set_property src_info {type:XDC file:7 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {pins[0]}]
set_property src_info {type:XDC file:7 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {pins[1]}]
set_property src_info {type:XDC file:7 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {pins[2]}]
set_property src_info {type:XDC file:7 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {pins[3]}]
set_property src_info {type:XDC file:7 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {LED[0]}]
set_property src_info {type:XDC file:7 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports {LED[1]}]
set_property src_info {type:XDC file:7 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {LED[2]}]
set_property src_info {type:XDC file:7 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {LED[3]}]
set_property src_info {type:XDC file:7 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {LED[4]}]
set_property src_info {type:XDC file:7 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {LED[5]}]
set_property src_info {type:XDC file:7 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {LED[6]}]
set_property src_info {type:XDC file:7 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {LED[7]}]
set_property src_info {type:XDC file:7 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports {LED[8]}]
set_property src_info {type:XDC file:7 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {LED[9]}]
set_property src_info {type:XDC file:7 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {LED[10]}]
set_property src_info {type:XDC file:7 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {LED[11]}]
set_property src_info {type:XDC file:7 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {LED[12]}]
set_property src_info {type:XDC file:7 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports {switches[0]}]
set_property src_info {type:XDC file:7 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {switches[1]}]
set_property src_info {type:XDC file:7 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports {switches[2]}]
set_property src_info {type:XDC file:7 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {switches[3]}]
set_property src_info {type:XDC file:7 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {switches[4]}]
set_property src_info {type:XDC file:8 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}]
set_property src_info {type:XDC file:8 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}]
set_property src_info {type:XDC file:8 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}]
set_property src_info {type:XDC file:8 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1}]
set_property src_info {type:XDC file:8 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]
set_property src_info {type:XDC file:8 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]
set_property src_info {type:XDC file:8 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]
